[pigeon] fix: Apply correct ThrowError success callback (#11585)
Building in  Visual Studio 2026 gives the following error:

```
error C2664: 'void core_tests_pigeontest::FlutterIntegrationCoreApi::ThrowError(std::function<void (const flutter::EncodableValue *)> &&,std::function<void (const core_tests_pigeontest::FlutterError &)> &&)': cannot convert argument 1 from 'test_plugin::TestPlugin::CallFlutterThrowError::<lambda_1>' to 'std::function<void (const flutter::EncodableValue *)> &&'
```

This is likely due to https://stackoverflow.com/a/79894278/5164462 so the compiler does not allow unsuited call parameters.

Towards https://github.com/flutter/flutter/issues/185597

## Pre-Review Checklist

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[^1]: Regular contributors who have demonstrated familiarity with the repository guidelines only need to comment if the PR is not auto-exempted by repo tooling.